our_blog_api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("posts/", include("posts.urls")),
    path("admin/", admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="post"),
]

yit/urls.py
from django.contrib import admin
from django.urls import include, path

from yit.views import health, index

urlpatterns = [
    path("", index),
    path("health", health),
    path("posts/", include("posts.urls")),
    path("admin/", admin.site.urls),
]

posts/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100, null=False)
    image_url = models.CharField(max_length=100, null=True)
    body = models.TextField(null=False)
    pub_date = models.DateTimeField("date published", null=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.CharField(max_length=254, unique=True, null=False)

posts/views.py
from django.views import generic

from .models import Post


class IndexView(generic.ListView):
    template_name = "posts/index.html"
    context_object_name = "latest_posts"
    model = Post
    paginate_by = 2
    ordering = ["-pub_date"]


class DetailView(generic.DetailView):
    model = Post
    template_name = "posts/detail.html"

yit/views.py
from django.http import HttpResponse
from django.shortcuts import render


def health(request):
    return HttpResponse("OK", status=200)


def index(request):
    return render(request, "yit/index.html")

posts/templates/posts/detail.html
<h1>{{ post.title }}</h1> - {{ post.author.username }}

<p>
{{ post.body }}
</p>

posts/templates/posts/index.html
{% if latest_posts %}
    <ul>
    {% for post in latest_posts %}
    <li><a href="{% url 'posts:post' post.id %}">{{ post.title }} - {{ post.author.username }}</a></li>
    {% endfor %}
    </ul>
    {% if is_paginated %}
      <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
              <a href="{% url 'posts:index' %}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
              <a href="{% url 'posts:index' %}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
      </div>
    {% endif %}
{% else %}
    <p>No posts are available.</p>
{% endif %}

templates/yit/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Yemeni's In Tech</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Yemeni's in Tech Homepage">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Lato:100,300" rel="stylesheet">
    <style>
      input,button {
        display: block;
      }
      .flashes {
        background-color: yellow;
      }
      .loader {
        border: 5px solid #f3f3f3;
        border-radius: 50%;
        border-top: 5px solid #3498db;
        width: 10px;
        height: 10px;
        animation: spin 2s linear infinite;
      }
      .error {
        color: red;
      }
      .success {
        color: green;
      }
      @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
      }
    </style>
    {% block css %}
    {% endblock %}
	</head>
	<body>
    <!-- What's up you sneaky rascal -->
    <h1>Hello World :)</h1>

    <script
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"
    </script>
    <script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"
    </script>
	</body>
</html>